feat(website): i18n ja (#3468)
Co-authored-by: liyang <liyang@selectdb.com>
Co-authored-by: Jeffrey <color.dove@gmail.com>

diff --git a/.github/workflows/manual-deploy-website.yml b/.github/workflows/manual-deploy-website.yml
--- a/.github/workflows/manual-deploy-website.yml
+++ b/.github/workflows/manual-deploy-website.yml
@@ -41,7 +41,15 @@ jobs:
                   npm install -g yarn
                   yarn cache clean
                   export NODE_OPTIONS=--max-old-space-size=8192
-                  yarn && yarn build
+                  yarn
+                  PWA_SERVICE_WORKER_URL=https://doris.apache.org/sw.js yarn docusaurus build --locale en --locale zh-CN
+                  if [ ! -d "./ja-build" ]; then
+                      echo "ja-build directory not found, aborting to avoid publishing incorrect ja content."
+                      exit 1
+                  fi
+                  rm -rf ./build/ja
+                  mkdir -p ./build/ja
+                  cp -a ./ja-build/. ./build/ja/
                   touch build/.dummy
                   cp .asf-site.yaml ./build/.asf.yaml
                   cp versions.json ./build/
